#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         1
bspc config normal_border_color "#292e42"
bspc config focused_border_color  "#7aa2f7"
bpsc config top_padding 50
bspc config window_gap           14

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a firefox:Toolkit state=floating follow=on
bspc rule -a Blueman-manager state=floating follow=on managed=off
bspc rule -a Pavucontrol state=floating follow=on managed=off
bspc rule -a KeePassXC desktop='^5' state=floating follow=on managed=off
bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Spotify desktop='^4' state=floating
bspc rule -a Chromium desktop='^3' state=floating
bspc rule -a Celluloid desktop='^4' state=floating managed=off
bspc rule -a Thunar state=floating managed=off
bspc rule -a qBittorrent state=floating managed=off
bspc rule -a "ONLYOFFICE Desktop Editors" desktop='^3' follow=on state=floating managed=off

